# Generated by Django 5.0.2 on 2024-02-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
